/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.mycompany.directorio;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Estudiantes
 */
public class listaContactos extends javax.swing.JFrame {

    /**
     * Creates new form listaContactos
     */
    public listaContactos() {
        initComponents();
        addElementToDelete();
        showContacts();
    }
    
    public void showContacts(){
        
        jTextArea1.setText("");
        
        Contactoform form = new Contactoform();
        ArrayList<Contacto> array = Contactoform.listaContactos;
        int numberOfResults = array.size();

        if(numberOfResults != 0){
            for(int i = 0; i < numberOfResults; i ++){
        
            String name = array.get(i).nombre;
            String email = array.get(i).correoelectronico;
            String streetAddress = array.get(i).direccionpostal;
            String phoneNumber = array.get(i).telefono;
            
            jTextArea1.append("\n====================");
            jTextArea1.append("\nNombre: " + name);
            jTextArea1.append("\nNumero: " + phoneNumber);
            jTextArea1.append("\nCorreo: " + email);
            jTextArea1.append("\nDireccion: " + streetAddress);
            jTextArea1.append("\n====================");
               
            }
        }
    
    }
    
    
    public void addElementToDelete(){
        
        listUsers.removeAllItems();
        
        Contactoform form = new Contactoform();
        ArrayList<Contacto> array = Contactoform.listaContactos;
        int numberOfResults = array.size();
        
        for(int i = 0; i < numberOfResults; i ++){
        
            String nameUser = array.get(i).nombre;
            
            listUsers.addItem(nameUser);
               
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        goBackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        deleteOption = new javax.swing.JButton();
        filterByName = new javax.swing.JButton();
        listUsers = new javax.swing.JComboBox<>();
        showAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTA DE CONTACTOS");

        goBackButton.setText("Volver atrás ");
        goBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackButtonMouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        deleteOption.setText("Eliminar contacto");
        deleteOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteOptionMouseClicked(evt);
            }
        });

        filterByName.setText("Filtrar contacto por nombre");
        filterByName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterByNameMouseClicked(evt);
            }
        });

        showAll.setText("Mostrar todo");
        showAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAllMouseClicked(evt);
            }
        });
        showAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(filterByName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(listUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteOption, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                            .addComponent(goBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showAll)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(filterByName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackButtonMouseClicked
       
        this.setVisible(false);
        
        Contactoform otherpage = new Contactoform();
        otherpage.setVisible(true);
        
        
    }//GEN-LAST:event_goBackButtonMouseClicked

    private void filterByNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterByNameMouseClicked
        
        jTextArea1.setText("");
        
        String name = JOptionPane.showInputDialog("Nombre de la persona que desea buscar:");
        
        Contactoform form = new Contactoform();
        ArrayList<Contacto> array = Contactoform.listaContactos;
        int numberOfResults = array.size();

        if(numberOfResults != 0){
            for(int i = 0; i < numberOfResults; i ++){
        
            String nameToFind = array.get(i).nombre;
            
                if(nameToFind.equals(name)){
                    
                    String nameFilter = array.get(i).nombre;
                    String emailFilter = array.get(i).correoelectronico;
                    String streetAddressFilter = array.get(i).direccionpostal;
                    String phoneNumberFilter = array.get(i).telefono;

                    jTextArea1.append("\n====================");
                    jTextArea1.append("\nNombre: " + nameFilter);
                    jTextArea1.append("\nNumero: " + phoneNumberFilter);
                    jTextArea1.append("\nCorreo: " + emailFilter);
                    jTextArea1.append("\nDireccion: " + streetAddressFilter);
                    jTextArea1.append("\n====================");
                }
            }
        }
        
    }//GEN-LAST:event_filterByNameMouseClicked

    private void deleteOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteOptionMouseClicked
        
        String option = (String) listUsers.getSelectedItem();
        Contactoform form = new Contactoform();
        ArrayList<Contacto> array = Contactoform.listaContactos;
        int numberOfResults = array.size();
        
        for(int i = 0; i < numberOfResults; i ++){
        
            String nameToFind = array.get(i).nombre;
            
                if(nameToFind.equals(option)){
                    
                    jTextArea1.setText("");
                    jTextArea1.append("\n====================");
                    jTextArea1.append("\nContacto eliminado");
                    jTextArea1.append("\n====================");
                    array.remove(i);
                    addElementToDelete();
                    
                }
            }
       

    }//GEN-LAST:event_deleteOptionMouseClicked

    private void showAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showAllActionPerformed

    private void showAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAllMouseClicked
        showContacts();
    }//GEN-LAST:event_showAllMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listaContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listaContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listaContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listaContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listaContactos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteOption;
    private javax.swing.JButton filterByName;
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> listUsers;
    private javax.swing.JButton showAll;
    // End of variables declaration//GEN-END:variables

}
